"""create certificates and user_certificates tables

Revision ID: 022bc49e02e8
Revises: 9e36691b8c7f
Create Date: 2026-07-06 16:46:30.851489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022bc49e02e8'
down_revision: Union[str, Sequence[str], None] = '9e36691b8c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: esta migration foi gerada por --autogenerate junto com um trabalho paralelo
    # de outro domínio (badges/user_badges, GAME-005), rodando na mesma sessão contra o
    # mesmo banco. As tabelas 'badges' e 'user_badges' foram removidas manualmente deste
    # arquivo — pertencem à migration própria do domínio badges, não a este (GAME-006).
    op.create_table('certificates',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_track_id'), 'certificates', ['track_id'], unique=False)
    op.create_table('user_certificates',
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('validation_code', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificates_certificate_id'), 'user_certificates', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_user_certificates_user_id'), 'user_certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_certificates_validation_code'), 'user_certificates', ['validation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_certificates_validation_code'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_user_id'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_certificate_id'), table_name='user_certificates')
    op.drop_table('user_certificates')
    op.drop_index(op.f('ix_certificates_track_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
