"""create user_leagues table

Revision ID: dc18282faa13
Revises: ac57cacc72cc
Create Date: 2026-07-07 10:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc18282faa13"
down_revision: str | Sequence[str] | None = "ac57cacc72cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    league_enum = sa.Enum(
        "bronze",
        "prata",
        "ouro",
        "platina",
        "diamante",
        "master",
        "legend",
        name="league",
    )
    op.create_table(
        "user_leagues",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("league", league_enum, nullable=False),
        sa.Column("group_number", sa.Integer(), nullable=False),
        sa.Column("entered_league_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_processed_iso_year", sa.Integer(), nullable=False),
        sa.Column("last_processed_iso_week", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_leagues_user_id"),
    )
    op.create_index(op.f("ix_user_leagues_user_id"), "user_leagues", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_leagues_user_id"), table_name="user_leagues")
    op.drop_table("user_leagues")
    league_enum = sa.Enum(
        "bronze",
        "prata",
        "ouro",
        "platina",
        "diamante",
        "master",
        "legend",
        name="league",
    )
    league_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
